### ISSUE TITLE
Adjust primo search result to current katalog

### ISSUE THREAD

**Issue by msievers** [ubpb/katalog_ubpb#1]
This issue is meant to sum up commits related to this topic.

**Comment by msievers** [comment]
In order to implement old catalog journal holdings, the new catalog uses the DC terms field accrualPolicy with a free choosen value (see ubpb/katalog#1)

**Comment by msievers** [comment]
Jorunal holdings implemented via accrual policy.

**Comment by renspr** [comment]
Not relevant anymore.
