### ISSUE TITLE
Fernleihen nicht verlinken

### ISSUE THREAD

**Issue by renspr** [ubpb/katalog_ubpb#100]
In der Liste der Ausleihen, sollten Fernleihen nicht verlinkt werden, da diese im Katalog keine Treffer haben.

Beispiel:
<img width="838" alt="bildschirmfoto 2016-01-21 um 10 44 37" src="https://cloud.githubusercontent.com/assets/495000/12476804/03c6ab02-c02c-11e5-9aee-5318939d0376.png">

**Comment by msievers** [comment]
Sollte behoben sein.
