### ISSUE TITLE
BiBTeX Export - Export von DOI

### ISSUE THREAD

**Issue by Siedlerchr** [ubpb/katalog_ubpb#108]
Hallo,

leider wird die DOI nicht mit exportiert: 
Wünschenswert wäre es die DOI in das entsprechende BibteX DOI Feld zu exportieren und/order in das URL Feld, dann als  http://dx.doi.org/<doi> 

Beispiel Record:
https://katalog.ub.uni-paderborn.de/primo_central/records/acm62658

**Comment by msievers** [comment]
@Siedlerchr Vielen Dank, dass du dir die Mühe gemacht hast nen Issue anzulegen.

Ich habe den DOI Eintrag zum BibTeX Export hinzugefügt. Für das von dir angegebene Beispiel wird nun folgendes BibTeX erzeugt

```bib
@{ells-a,
  author = {Ells, Rick},
  note = {<p><p>Hypermedia will soon become a basic tool for providing information support for all sizes of computing systems. Documentation professionals will need to make an efficient transition to this new method of presenting information. Structural aspects of existing hardcopy documents and on-line help can serve as a guide, but some rethinking of how information is presented will be needed to take full advantage of the potential of hypermedia.</p></p>},
  key = {acm62658},
  isbn = {0897912861, 9780897912860},
  series = {Proceedings of the 16th annual ACM SIGUCCS Conference on user services, 01 October 1988, pp.363-368},
  title = {Hypermedia, help and how-to},
  doi = {10.1145/62548.62658},
  url = {https://dx.doi.org/10.1145/62548.62658}
}
```

Wenn das für dich ok ist und wir unsererseits keine Probleme damit feststellen, werden wir das denke ich zeitnah (innerhalb der nächsten Tage) produktiv ausrollen. Ich schließe den Issue mit nem entsprechenden Kommentar sobald das in Produktion aktiv ist.

**Comment by renspr** [comment]
Fix ist nun im Produktionssystem.
