### ISSUE TITLE
Suchergebnis nicht persistent

### ISSUE THREAD

**Issue by renspr** [ubpb/katalog_ubpb#22]
Gemeldet von: WE

WE merkt an: Es ist unschön die Recherche zu verlieren, wenn man nach einer Recherche von einer Detailseite auf "Anmelden" klickt. Der return_to Parameter greift zwar und man landet nach dem anmelden wieder auf der Detailseite aber der Recherchekontext ist weg.

Haben wir eine Chance den SearchRequest zu halten? Hatten wir das nicht mit dem Flash-Object im Griff? @msievers

**Comment by msievers** [comment]
Die folgende Commits sollten das Problem (global) beheben.
* 594fd6c31b2f2c1edbb110a05ebd7aeb9a4011d2
* e9c9869504ca6c6d3fd85cff4d1b5bb4e94bc833

**Comment by renspr** [comment]
Eine "globale" Lösung hat sich als nicht sinnvoll herausgestellt. Für die Detailansicht wurde über den return path eine entsprechende Lösung gesetzt.
