### ISSUE TITLE
Darstellung nicht korrekt für PAD_ALEPH001808642

### ISSUE THREAD

**Issue by renspr** [ubpb/katalog_ubpb#25]
Gemeldet von: WE

Bei dem folgenden Titel ist die Darstellung nicht korrekt: /records/PAD_ALEPH001808642?scope=local

Im Titel steht: Ziemlich beste Freunde [Elektronische Ressource]
Im Produktionssystem steht jedoch: Ziemlich beste Freunde [Bildtonträger]

Wahrscheinlich ein Fehler in der Normalisierung.

Zusätzlich fällt auf, dass keine Exemplare angegeben werden, aber im Produktionssystem schon. Der Grund liegt vermutlich am alten Datenstand vom Aleph Testsystem.

**Comment by msievers** [comment]
Die Daten sind zumindest bzgl. des Datenstandes der geladen ist ok.

[PAD01.001808642.PRIMO.xml.txt](https://github.com/ubpb/katalog_ubpb/files/37671/PAD01.001808642.PRIMO.xml.txt)

**Comment by msievers** [comment]
Daten in Alephtest sind veraltet. Ein Test gegen Aleph Produktion zeigt das erwartete Verhalten mit Exemplaren.

**Comment by renspr** [comment]
Ja, aber der Teil im Titel ist trotzdem "falsch" bzw. anders.
