### ISSUE TITLE
Standort-Codes in Spalte "Standort" erforderlich?

### ISSUE THREAD

**Issue by renspr** [ubpb/katalog_ubpb#26]
Im Produktionssystem zeigen wir in der Spalte "Standort" z30-collection-code an (z.B. 96 Magazin). Diese Spalte wird nur angezeigt wenn min. ein Exemplar einen anderen Standort hat als "Fachbibliothek".

Die neue Spalte Standort wird nun immer angezeigt und benutzt einheitliche Begriffe wie "Ebene 3", "Magazin" etc. Der Standort-Code wird nicht angezeigt. WE war dies aufgefallen. WE klärt nun ob für die Information der Standort-Code notwendig ist. Der Nutzer kann damit i.d.R. nichts anfangen.

**Comment by msievers** [comment]
Soweit ich mich recht erinnere werden die Standortcodes in der Standortspalte nicht benötigt. Es handelte sich dabei auch mehr im die Frage ob und nicht um eine konkrete Anforderung.
