### ISSUE TITLE
Icons fehlen für Materialarten

### ISSUE THREAD

**Issue by renspr** [ubpb/katalog_ubpb#35]
Aktuell wird für jeden Titel ein Buch-Symbol angezeigt wenn kein Cover geladen werden kann. Für die gängigen Materialtypen sollten entsprechende Icons gewählt werden.

Jedes Icon sollte in SM und LG (für Detailansicht) existieren.

**Comment by msievers** [comment]
Hierfür müssen erst die entsprechenden PNGs erstellt werden. siehe #103
