### ISSUE TITLE
Fehlende Bestandsanzeige

### ISSUE THREAD

**Issue by renspr** [ubpb/katalog_ubpb#50]
Gemeldet von: LT

Beispiel:
Titel: "Bildung + Lernen" (Systemnummer 001107890)
In der ZDB gibt es dazu einen Lokalsatz, in Aleph allerdings weder Bestell- noch Abodatensatz. Der ZDB-Lokalsatz wurde in PAD60 geliefert (ID HL006360752 )

**Comment by renspr** [comment]
Aktuell im Produktionssystem genau so.

**Comment by msievers** [comment]
Kann das Problem nicht nachvollziehen. Im Produktionssystem ist die Darstellung identisch.
