### ISSUE TITLE
Unvollständige Bestandsanzeige

### ISSUE THREAD

**Issue by renspr** [ubpb/katalog_ubpb#51]
Gemeldet von: LT

Es taucht nur die erste Zeile der Bestandsanzeige auf, die zweite Zeile ist unvollständig abgebildet, die dritte Zeile fehlt komplett. Der Zusatzhinweis "Repr. 1962" fehlt ebenfalls
Titel: "American Mathematical Society : Translations (Systemnummer 001448117)

**Comment by renspr** [comment]
Unklar was das Problem ist. Produktionssystem sieht identisch aus.

**Comment by msievers** [comment]
Kann ich anhand der Systemnummer ebenfalls nicht nachvollziehen, da identisch mit Produktionssystem.

**Comment by renspr** [comment]
Magst Du LT mal anrufen und nochmal nachfragen?
