### ISSUE TITLE
Suche nach Bernard Salanié liefert keine Treffer

### ISSUE THREAD

**Issue by renspr** [ubpb/katalog_ubpb#65]
Gemeldet von: PT

"Ich habe in der neuen Version des Katalogs nach dem Autor Bernard Salanié gesucht. Leider bekomme ich keinen Treffer, wenn ich "salanie" suche, sondern nur, wenn ich den Akzent mit eingebe."

**Comment by msievers** [comment]
Ich hatte ASCII Folding bis dato nicht im `default` Analyzer, sondern nur die deutschen Umlaute manuell durch ihre `ae`, `oe`. `ue` Äquivalente ersetzt.

Um das Problem zu beheben wird jetzt einfach der Default `asciifolding` Tokenfilter hinter den Tokerfiltern zur manuellen Umsetzungen der deutschen Umlaute eingefügt. Dahinter ist dabei wichtig.

siehe https://github.com/ubpb/metacrunch-ubpb/commit/3a8c4a42fa9570428efd77c49d54707ae6aef587
