### ISSUE TITLE
OR, NOT nicht möglich

### ISSUE THREAD

**Issue by renspr** [ubpb/katalog_ubpb#73]
Primo verwendet für boolsche Operatoren AND, OR, und NOT. ES simple_query_string nutzt +, | und -. Primo erlaubt zudem deutsche Versionen UND, ODER und NICHT.

Können / sollten wir entsprechende Alias-Formen erlauben?

**Comment by msievers** [comment]
Durch die Umstellung auf `query_string` wieder gefixt.
