### ISSUE TITLE
Handapparat sollte rot markiert sein

### ISSUE THREAD

**Issue by renspr** [ubpb/katalog_ubpb#77]
Gemeldet von: WE

Bei https://katalog-test.ub.uni-paderborn.de/local/records/001704082 wird das Exemplar im Handapparat gelb markiert. Sollte rot markiert werden.

Außerdem wird die Spalte "Magazinbestellung" angezeigt, obwohl kein Exemplar bestellbar ist. => Closed by b2a2b35b8cdbdc9bafd6544bcc42649b79e2eb08

**Comment by msievers** [comment]
Handapparat kann man rot machen. Grundsätzlich bedeutet rot ja sowas wie "geht gar nicht". Bei einem Handapparat besteht grundsätzlich immer noch (die vielleicht auch etwas theoretische) Möglichkeit, den Inhaber zu kontaktieren und zu fragen, ob er das Buch/Teile zur Verfügung stellen könnte.

**Comment by msievers** [comment]
Aus eigener Erfahrung weiß ich, dass man z.B. im Rahmen von Prüfungsvorbereitungen häufig nicht das Buch braucht, sondern lediglich ein paar Seiten mit einem bestimmten Beweis. Dabei würde es völlig ausreichen, wenn einem Mitarbeiter X/Professor Y dieses Buch vielleicht nur 10 Minuten zum kopieren einiger Seiten überlassen würde.

**Comment by renspr** [comment]
Das war der Grund warum ich das Gelb gemacht habe. Aber das wird nur gemacht wenn kein anderes Exemplar existiert. Ich will aber nicht anfangen und den Status basierend auf dem Status anderer Exemplare bestimmen. Daher können wir hier nur rot anzeigen.
