### ISSUE TITLE
"Ich-Identität" liefert kein gutes Relevanz Ranking

### ISSUE THREAD

**Issue by renspr** [ubpb/katalog_ubpb#80]
Gemeldet von: HU

Sucht man nach zusammengesetzten Wörtern wie "Ich-Identität" erhält man viele Treffer mit "Ich" und "Identität" jedoch keine mit "Ich-Identität".

Der Grund liegt wahrscheinlich im Token-Filter. Ich-Identität wird zu "Ich" und "Identität". Der Filter muss in diesem Fall so eingestellt werden, dass das "Original" erhalten bleibt.

**Comment by msievers** [comment]
`preserve_original: true` in `load_index` https://github.com/ubpb/metacrunch-ubpb/commit/2916afef89b06b200b8788b19c890710f1026838

**Comment by msievers** [comment]
Fullload läuft. Umschaltung des Alias erfolgt voraussichtlich noch heute Abend nach erfolgreichem Ladevorgang.

**Comment by renspr** [comment]
Nach der Änderung sieht das jetzt gut aus.
