### ISSUE TITLE
Verlängern Button wird nicht immer korrekt angezeigt

### ISSUE THREAD

**Issue by renspr** [ubpb/katalog_ubpb#9]
Im Konto von Frau He. wird unter "Ausgeliehene Medien" bei einigen Ausleihen der Knopf "Verlängern" nicht angezeigt.

![unbenannt](https://cloud.githubusercontent.com/assets/495000/11089361/6549dafc-8869-11e5-9251-a6fb1dae7939.png)

**Comment by msievers** [comment]
Tests mit dem Benutzerkonto von hs haben keine Abweichung zwischen dem renewable Status einer Ausleihe und dem Ergebnis eines Loan-Renew-API-Calls gezeigt. Alle Ausleihen welche mit "N" markiert waren, konnten nicht verlängert werden.

**Comment by renspr** [comment]
Ok. Wir sollten dann in diesem Fall dort hinschreiben "Verlängerung nicht möglich". Das macht es deutlicher als einfach nur keinen Knopf anzuzeigen.

**Comment by msievers** [comment]
Stimmt, irgendwas sollten wir rendern. Vielleicht einfach den Knopf in einem disabled State oder einen Text der Form "Ausleihen nicht möglich". Das ist nachher Geschmackssache.
