### ISSUE TITLE
Trunkierungen welche Umlaute enthalten führen zu leeren Treffermengen

### ISSUE THREAD

**Issue by renspr** [ubpb/katalog_ubpb#91]
Gemeldet von: HL

Beim der Suche nach `glück*` ist das Resultat eine leere Treffermenge. Der erwartete Wert wäre jedoch eine Treffermenge, welche Worte wie `Glück`, `glücklich`, etc. enthält.

**Comment by msievers** [comment]
Das Problem liegt anscheinend darin, dass Rahmen der Indizierung Umlaute auf ihre `ue`, `ae`, `oe` Pandants umgesetzt werden. Wenn man nun nach `glück` trunkiert, scheinen aus irgendeinem Grund die Tokenfilter, welche für die Umsetzung der Umlaute verantwortlich sind, nicht zu greifen.

**Comment by msievers** [comment]
Das Problem wurde durch https://github.com/ubpb/katalog_ubpb/commit/2670912abaabd97ddd75b4836d5f782fd100c5b4 behoben.

Die dort vorgenommen Lösung umgeht das Problem, in dem (simple)_query_string Queries vor ihrer Übergabe an den generischen Elasticsearch Adapter von Umlauten befreit werden, indem diese durch ihre `u` Equivalente ersetzt werden.
